### ISSUE TITLE
Update causes Nginx Error '104: Connection reset by peer while reading response header from upstream'

### ISSUE THREAD

**Issue by michi-z** [justbetter/magento2-sentry#76] opened 2021-02-23 14:59 UTC
We run a Magneto 2.2.6 Shop and wanted to update the sentry extension to a newer version. We used the 0.6.2 version too long. Composer installed the version 2.2.3.

After that we got some times the Http Error 502 'Bad Gateway'. It was caused bei an nginx error (104: Connection reset by peer while reading response header from upstream) that was caused by an exiting php.

Because the error is not easiliy repeated, we wrote a random test to verify it.

So on PHP 7.1 with Magento 2.2.6 the problem is there and bad because whole pages are not delivered.

We tried to find the cause of the problem also with the help of our hoster but with no results.

With Magento 2.3.2 and PHP 7.3 the problem is gone. So we will concentrate on that.

**Comment by medialoungeml** [comment] 2021-03-01 15:27
We had the same issue using PHP 7.1 and Magento 2.2.6

We haven't noticed it on newer M2 and PHP versions.

**Comment by indykoning** [comment] 2022-10-11 15:05
I think this may be related to 
https://magento.stackexchange.com/questions/268896/upstream-sent-too-big-header-while-reading-response-header-from-upstream
It can be an issue if you have many different blocks, widgets and the like on a page.

Or just as likely your PHP running into a memory limit or a timeout. I suggest having a look in your `/var/log/php*-fpm.log` when it happens.

I'm closing this issue for now as i'm thinking it's more likely server configuration and coincidence that Sentry is pushing it over the edge sometimes.
Feel free to reopen if it is still an issue and certain to be caused by Sentry

**Closed by indykoning** 2022-10-11 15:05 UTC
