### ISSUE TITLE
Circular dependency in 2.1.0

### ISSUE THREAD

**Issue by peterjaap** [justbetter/magento2-sentry#40] opened 2019-11-25 11:04 UTC
Magento 2.3.3
magento2-sentry 2.1.0

```
php bin/magento app:config:dump
Circular dependency: JustBetter\Sentry\Plugin\MonologPlugin depends on Magento\Framework\App\Helper\Context and vice versa.#0 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Just
Better\\Sent...')
#1 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('JustBetter\\Sent...')
#2 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Psr\\Log\\LoggerI...', NULL, 'logger', 'Magento\\Framewo...')
#3 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#4 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#5 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#6 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#7 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'context', 'JustBetter\\Sent...')
#8 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('JustBetter\\Sent...', Array, Array)
#9 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('JustBetter\\Sent...', Array, Array)
#10 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('JustBetter\\Sent...')
#11 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('JustBetter\\Sent...')
#12 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'JustBetter\\Sent...', NULL, 'data', 'JustBetter\\Sent...')
#13 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('JustBetter\\Sent...', Array, Array)
#14 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('JustBetter\\Sent...', Array, Array)
#15 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('JustBetter\\Sent...')
#16 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('JustBetter\\Sent...')
#17 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Psr\\Log\\LoggerI...', NULL, 'logger', 'Magento\\Framewo...')
#18 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#19 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#20 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#21 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#22 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'logger', 'Magento\\Framewo...')
#23 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#24 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#25 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#26 /data/clientname/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(197): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#27 /data/clientname/magento2/vendor/magento/framework/App/Cache/Frontend/Factory.php(161): Magento\Framework\App\Cache\Frontend\Factory->_applyDecorators(Object(Magento\Framework\Cache\Frontend\Decorator\TagScope))
#28 /data/clientname/magento2/vendor/magento/framework/App/Cache/Frontend/Pool.php(67): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#29 /data/clientname/magento2/vendor/magento/framework/App/Cache/Frontend/Pool.php(146): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#30 /data/clientname/magento2/vendor/magento/framework/App/Cache.php(38): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#31 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): Magento\Framework\App\Cache->__construct(Object(Magento\Framework\App\Cache\Frontend\Pool))
#32 /data/clientname/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#33 /data/clientname/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#34 /data/clientname/magento2/vendor/magento/framework/App/Cache/Proxy.php(44): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#35 /data/clientname/magento2/vendor/magento/framework/App/Cache/Proxy.php(67): Magento\Framework\App\Cache\Proxy->_getCache()
#36 /data/clientname/magento2/vendor/magento/framework/App/ProductMetadata.php(80): Magento\Framework\App\Cache\Proxy->load('mage-version')
#37 /data/clientname/magento2/vendor/magento/framework/Console/Cli.php(92): Magento\Framework\App\ProductMetadata->getVersion()
#38 /data/clientname/magento2/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#39 {main}

```

**Comment by rakibabu** [comment] 2019-12-12 09:35
Hi @peterjaap ,

On a fresh install with Magento 2.3.3 I can't reproduce this issue. Can you tell me how I can reproduce this issue?

**Comment by Niko9911** [comment] 2019-12-12 10:30
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-depen.html#sample-circular-dependencies-report

**Comment by Niko9911** [comment] 2019-12-12 10:31
This prevents usage of this module.

**Comment by rakibabu** [comment] 2019-12-12 13:21
@Niko9911 ,

Can you please provide us with detailed information? As example you can use this issue template;

https://github.com/justbetter/magento2-sentry/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Niko9911** [comment] 2019-12-12 13:28
@rakibabu see #44 everything else outside of that cannot be provided due NDA. Your template is useless to report this kind issues.

**Comment by rakibabu** [comment] 2019-12-12 15:04
@Niko9911 ,

What do you propose to fix this? I can't reproduce this issue.

**Comment by Niko9911** [comment] 2019-12-12 22:28
@rakibabu 

Thanks for contributing!

**Comment by rakibabu** [comment] 2019-12-13 10:35
@Niko9911 ,

No problem, you're welcome 👍

**Comment by Zyles** [comment] 2019-12-27 12:20
Same problem on 2.3.3.

Fix?

**Comment by GautierI** [comment] 2020-01-22 16:13
Same problem on 2.3.3.

Still no fix ?

**Comment by peterjaap** [comment] 2020-01-22 18:49
I can't reproduce it anymore either. But apparently other people can so maybe other people can help out getting a reproducable setup. I'm unsubscribing from this thread.

**Comment by kerlama** [comment] 2020-01-29 12:25
Hi,

I overcome this by flushing redis cache, and it worked. Not sure what's the solution if you dont use redis on your instance.

Ivan

**Comment by Alainvdz99** [comment] 2020-02-24 13:26
Just do a reinstall and it should disappear

**Comment by indykoning** [comment] 2020-07-07 07:26
This issue seems to be solved by flushing Redis cache or reinstalling.
I'll be closing this issue. Feel free to reopen it if the issue does still persist.

**Closed by indykoning** 2020-07-07 07:26 UTC

**Comment by GeKVe** [comment] 2024-11-29 14:46
Got this without running redis cache. Can confirm reinstalling the module worked.
